from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer

#create fastapi application
app = FastAPI()

#load the embedding model once it starts which prevents it from loading for every request
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

class EmbeddingRequest(BaseModel):
    #text converted into an embedding
    text: str

class EmbeddingResponse(BaseModel):
    #vector representation generated by embedding model
    embedding: list[float]

@app.get("/health")
def health_check():
    return {
        "status" :"ok"
    }    

@app.post("/embed",response_model=EmbeddingResponse)#The response from this endpoint should follow the structure defined by EmbeddingResponse before...at 15 loc
def create_embedding(request: EmbeddingRequest):
    #reject empty input bcz nothing to embed
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="text cannot be empty",)


# generate embedding for the supplied text
    embedding = model.encode(request.text,normalize_embeddings=True,)

#convert returned numpy array into python list so fastapi can  serialize it as a json
    return {
    "embedding" : embedding.tolist()
}


# POST /embed
#     ↓
# FastAPI receives request
#     ↓
# Convert/validate request using EmbeddingRequest
#     ↓
# run create_embedding()
#     ↓
# generate embedding
#     ↓
# return response
#     ↓
# validate/serialize response as EmbeddingResponse
#     ↓
# send JSON back