from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer

# create fastapi application
app = FastAPI()

# load embedding model once at startup
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

class EmbeddingRequest(BaseModel):
    # text converted into an embedding
    text: str

class EmbeddingResponse(BaseModel):
    # vector representation generated by embedding model
    embedding: list[float]

@app.get("/health")
def health_check():
    return {
        "status" :"ok"
    }    

@app.post("/embed", response_model=EmbeddingResponse)
def create_embedding(request: EmbeddingRequest):
    # reject empty input
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="text cannot be empty")

    # generate embedding for supplied text
    embedding = model.encode(request.text, normalize_embeddings=True)

    # convert numpy array to python list for json serialization
    return {
        "embedding": embedding.tolist()
    }
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8001)